// This file is generated by Slice Machine. Update with care!

import Blog from './Blog';
import Home from './Home';

export {
	Blog,
	Home,
};

export const components = {
	blog: Blog,
	home: Home,
};
