import MainLayout from "../components/MainLayout";

export default function contact() {
  return (
    <MainLayout>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
      <h1>contact</h1>
    </MainLayout>
  )
}
